config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  get 'expenses/index'
  resources :expenses
  resources :incomes
  root 'welcome#index'# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user
 
end

app/models/income.rb
class Income < ApplicationRecord
  belongs_to :user


end

app/models/user.rb
class User < ApplicationRecord
  has_many :incomes
  has_many :expenses

  def total_expenses
    expenses.pluck(:amount).sum
  end

  def total_incomes
    incomes.pluck(:amount).sum
  end

  def profit_loss
    total_incomes - total_expenses
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
    @expenses = current_user.expenses
  end

  def new
    @expense = Expense.new
  end

  def create
    @expense = Expense.new(expense_params)
    @expense.user = current_user
    if @expense.save
      flash[:success] = "Expense was created successfully"
      redirect_to expenses_path(@expense)
    else
      render new
    end
  end

  def edit
    @expense = Expense.find(params[:id])
  end

  def update
    @expense = Expense.find(params[:id])
    if @expense.update(expense_params)
      flash[:notice] = "Expense was successfully updated"
      redirect_to expenses_path(@expense)
    else
      render "edit"
    end
  end

  def destroy
    @expense = Expense.find(params[:id])
    @expense.destroy
    flash[:danger] = "Expense was successfully deleted"
    redirect_to expenses_path(@expense)
  end

  private

  def expense_params
    params.require(:expense).permit(:amount, :description)
  end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  def index
    @incomes = current_user.incomes
  end

  def new
    @incomes = Income.new
  end

  def create
    @income = Income.new(income_params)
    @income.user = current_user
    if @income.save
      flash[:notice] = "Income was successfully created"
      redirect_to incomes_path(@income)
    else
      render "new"
    end
  end

  def edit
    @income = Income.find(params[:id])
  end

  def update
    @income = Income.find(params[:id])
    if @income.update(income_params)
      flash[:notice] = "Income was successfully updated"
      redirect_to incomes_path(@income)
    else
      render "edit"
    end
  end

  def destroy
    @income = Income.find(params[:id])
    @income.destroy
    flash[:danger] = "Budget was successfully deleted"
    redirect_to incomes_path(@income)
  end

  private

  def income_params
    params.require(:income).permit(:amount, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @incomes = current_user.incomes.where(created_at: (params[:start_date].to_date)..(params[:end_date].to_date)).all
    @expenses = current_user.expenses.where(created_at: (params[:start_date].to_date)..(params[:end_date].to_date)).all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/expenses/_expense_form.html.erb
<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@expense, html: {class: "form-horizontal"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-8">
        <%= f.text_field :amount, class: "form-control", placeholder: "Expense", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-8">
        <%= f.text_area :description ,class: "form-control", placeholder: "Message of the Expense", autofocus: true %><br />
      </div>
    </div>
    <div class="form-group">
      <div class=" col-sm-offset-2 col-sm-2">
        <%= f.submit class:"btn btn-warning btn-lg" %>
      </div>
    </div>
   <% end %>
  </div>
</div>

app/views/expenses/edit.html.erb
<%= render  "expenses/expense_form" %>

app/views/expenses/index.html.erb
<h1 align="center"> All Expense</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Expense</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.amount %> </td>
        <td> <%= link_to "Edit Expense", edit_expense_path(expense),class: "btn btn-xs btn-primary" %></td>
        <td><%= link_to 'Delete', expense_path(expense), method: :delete, data: {confirm: "Are you sure?"} , class: "btn btn-xs btn-warning" %></td>
      </tr>
    <% end %>
    <hr>
    <td><b>Total Expense </b><mark><%=  current_user.total_expenses %></mark></td>
  </tbody>
</table>

app/views/expenses/new.html.erb
<%= render 'expenses/expense_form' %>

app/views/incomes/_income_form.html.erb
<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@incomes, html: { class: "form-horizontal" }) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-8">
          <%= f.text_field :amount, class: "form-control", placeholder: "Expense", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
          <div class="control-label col-sm-8">
            <%= f.text_area :description, class: "form-control", placeholder: "Message of the Expense", autofocus: true %><br />
          </div>
      </div>
      <div class="form-group">
        <div class=" col-sm-offset-2 col-sm-2">
          <%= f.submit class: "btn btn-warning btn-lg" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/incomes/edit.html.erb
<%= render 'income_form' %>

app/views/incomes/index.html.erb
<h1 class="center"> All Income</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Income</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @incomes.each do |income| %>
      <tr>
        <td><%= income.amount %> </td>
        <td> <%= link_to "Edit Income", edit_income_path(income), class: "btn btn-xs btn-primary" %></td>
        <td><%= link_to 'Delete', income_path(income), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger"%></td>
      </tr>
    <% end %>
    <td><b>Total income </b><mark><%= current_user.total_incomes %></mark></td>
    <div class="form-group">
      <%= link_to "logout", destroy_user_session_path, method: :delete, class: "btn btn-xs btn-primary" %>
    </div>
</table>

app/views/incomes/new.html.erb
<%= render 'income_form' %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to  "ProfitLoss App", root_path, class: "navbar-brand", id:" logo" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li> <%= link_to "Link" %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to "Action" %>
            <li>
              <%= link_to "Another Action" %></li>
            <li>
              <%= link_to "something here" %></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Link" %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to "Action" %></li>
            <li>
              <%= link_to "Another Action" %></li>
            <li>
              <%= link_to "something here" %></li>
          </ul>
        </li>
      </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "ProfitLossApp" %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= javascript_include_tag "application" %>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
</head>
<body>
  <div class="navbar navbar-default navbar-static-top">
    <div class="container">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">ProfitLossApp</a>
      <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Income", incomes_path  %></li>
          <li><%= link_to "Expense", expenses_path  %></li>
          <li><%= link_to "Add Income", new_income_path  %></li>
          <li><%= link_to "Add Expense", new_expense_path  %></li>
        </ul>
        <ul class="nav navbar-right col-md-4">
          <li class="col-md-8 user-name text-right">
            <i class="fa fa-user"></i>
          </li>
          <li class="col-md-4 logout">
            <%= link_to("logout", destroy_user_session_path,
                        class: "btn btn-xs btn-danger", method: :delete) %>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-9">
        <%= bootstrap_flash %>
        <%= yield %>
      </div>
    </div> <!-- /container -->
</body>
</html>

app/views/users/index.html.erb
<canvas id="myChart"></canvas>
<script>
var ctx = document.getElementById('myChart').getContext('2d');
var myPieChart = new Chart(ctx, {
    type: 'pie',
    data: {
        labels: ['Income', 'Expense', 'Profit'],
        datasets: [{
            label: '# of User',
            data: [ <%= current_user.total_incomes %>,
            <%= current_user.total_expenses %>,
            <%= current_user.profit_loss %>
            ],
            backgroundColor: [
                'rgba(255, 0, 0)',
                'rgba(255, 165, 0)',
                'rgba(0, 255, 0)',
      
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
</script>
<h1 align="center"> All Income</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Income</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @incomes.each do |income| %>
      <tr>
        <td><%= income.amount %> </td>
        <td> <%= link_to "Edit Income", edit_income_path(income) %></td>
        <td><%= link_to 'Delete', income_path(income), method: :delete, data: {confirm: "Are you sure?"} %></td>
      </tr>
    <% end %>
    <div class="form-group">
    </div>
  </tbody>
</table>
<h1 align="center"> All Expense</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Expense</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.amount %> </td>
        <td> <%= link_to "Edit Expense", edit_expense_path(expense),class: "btn btn-xs btn-primary" %></td>
        <td><%= link_to 'Delete', expense_path(expense), method: :delete, data: {confirm: "Are you sure?"} , class: "btn btn-xs btn-warning" %></td>
      </tr>
    <% end %>
    <hr>
  </tbody>
</table>

app/views/users/new.html.erb
<div class="center">
  <div class="form-group">
    <%= form_tag users_path, method: :get do %>
    <%= date_field_tag :start_date %>
    <%= date_field_tag :end_date %>
    <%= submit_tag  'search',  class: "btn btn-sm btn-primary" %>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="form-group">
   <%= link_to new_user_path remote: true, id: "new-item-link", class: "btn btn-sm btn-default round" do %> view by date income Portal
  <% end %>
</div>